info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /metrics/{metricDbId}:
    get:
      summary: Get the analysis metrics available on a server
      description: Get the analysis metrics available on a server
      parameters:
      - description: The unique identifier for a metric value
        in: path
        name: metricDbId
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/MetricSingleResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      tags:
      - Metrics
    put:
      summary: Update an existing Metric record
      description: |-
        Update an existing Metric record
      parameters:
      - description: The unique identifier for a file
        in: path
        name: metricDbId
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetricNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/MetricSingleResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      tags:
      - Metrics
components:
  responses:
    MetricSingleResponse:
      content:
        application/json:
          schema:
            title: MetricSingleResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                $ref: '#/components/schemas/Metric'
            required:
            - metadata
            - result
      description: OK
      headers: {}
      
