info:
  title: BrAPI
  version: ''
openapi: 3.1.0
paths: {}
components:
  schemas:
    ContentTypes:
      enum:
      - application/json
      - text/csv
      - text/tsv
      - application/flapjack
      type: string