info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  responses:
    MetabolomicsMatrixResponse:
      content:
        application/json:
          schema:
            title: MetabolomicsMatrixResponse
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                allOf:
                - $ref: '#/components/schemas/MetabolomicsInstance'
                - properties:
                    data:
                      items:
                        $ref: '#/components/schemas/MetabolomicsMatrixRow'
                      type: array
                  required:
                  - data
                  type: object
            required:
            - metadata
            - result
            type: object
      description: OK
      headers: {}
  schemas:
    MetabolomicsMatrixRow:
      type: object
      properties:
        observationUnitDbId:
          description: Identifier containing the unique observation unit linked to an experiment ID
          type: string
          example: e3675c4a
        sampleDbId:
          description: Identifier containing the unique sample name linked to an experiment ID
          type: string
          example: BB251_101
        tissueType:
          description: Description of the plant part (e.g. leaf) or the plant product (e.g. resin) from which the sample was taken, in the form of an accession number from Plant Ontology
          type: string
          example: PO:0009010; seed
        tissueDevStage:
          description: Stage in life of the plant structure during which the sample was taken, in the form of an accession number from Plant Ontology
          type: string
          example: PO:0001083, inflorescence development stage
        plantAge:
          description: Sample plant's age; numerical representation of days after planting
          type: integer
          example: 20
        specimenSource:
          description: Description of specimen source
          type: string
          example: USDA_GRIN_2020
        tissueCollectionTimestamp:
          description: Timestamp for tissue collection
          format: date-time
          type: string
          example: 2024-01-02 3:04:05
        tissueStorage:
          description: Where tissue is stored
          type: string
          example: -80 degrees
        comments:
          description: Any comments collected by the researcher during sample preparation and data collection
          type: string
          example: root
        row:
          description: description
          type: array
          example: ["0.0355", "0.1442", "0.4322", "0.5473"]
          items:
            type: string