info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /scales:
    get:
      summary: Get the Scales
      description: |-
        Returns a list of Scales available on a server.

        An Observation Variable has 3 critical parts; A Trait being observed, a Method for making the observation, and a Scale on which the observation can be measured and compared with other observations.
      parameters:
      - description: The unique identifier for a scale
        in: query
        name: scaleDbId
        required: false
        schema:
          type: string
      - description: The unique identifier for an observation variable
        in: query
        name: observationVariableDbId
        required: false
        schema:
          type: string
      - $ref: '#/components/parameters/externalReferenceID' 
      - $ref: '#/components/parameters/externalReferenceId'
      - $ref: '#/components/parameters/externalReferenceSource'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/ScaleListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Scales
    post:
      summary: Add new Scales
      description: Create new scale objects in the database
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ScaleNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/ScaleListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Scales
components:
  responses:
    ScaleListResponse:
      content:
        application/json:
          schema:
            title: ScaleListResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/Scale'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
      description: OK
      headers: {}
