plugins {
  id 'java'
}

ext {
  javaMainClass = 'org.brapi.schematools.cli.BrAPICommand'
  brapiSchemaToolsVersion = '0.73.0'
}

repositories {
  mavenCentral()
  maven {url 'https://central.sonatype.com/repository/maven-snapshots/'}
  maven {url 'https://s01.oss.sonatype.org/content/repositories/snapshots/'}
}

dependencies {
  implementation "org.brapi.brapi-schema-tools:brapi-schema-tools-cli:$brapiSchemaToolsVersion"
}

tasks.register('copyOpenApi', Copy) {
  from "../build/openapi.json"
  into "../Specification/Generated/"
  rename { String fileName ->
    fileName.replace("openapi.json", "brapi_openapi.json")
  }
  eachFile { println it.file }
}

tasks.register("validate", JavaExec) {
  group = 'BrAPI'
  description = 'Validate the Json Schema'
  classpath = sourceSets.main.runtimeClasspath
  mainClass = javaMainClass
  workingDir = '../'
  args = ['validate', 'Specification/BrAPI-Schema', '-x']
}

tasks.register("generateGraphQL", JavaExec) {
  group = 'BrAPI'
  description = 'Generate GraphQL schema from the Json Schema'
  classpath = sourceSets.main.runtimeClasspath
  mainClass = javaMainClass
  workingDir = '../'
  def filename = "Specification/Generated/brapi_generated.graphqls"
  args = ['generate',
          'Specification/BrAPI-Schema',
          '-l', 'GRAPHQL',
          '-f', filename,
          '-x',
          '-t',
          '-r']
}

tasks.register("generateOpenAPI", JavaExec) {
  group = 'BrAPI'
  description = 'Generate YAML OpenAPI schema per module from the Json Schema'
  classpath = sourceSets.main.runtimeClasspath
  mainClass = javaMainClass
  workingDir = '../'
  def filename = "Specification/Generated"
  def optionfilename = "generator/openapi-options.yaml"
  def metadatafilename = "generator/openapi-metadata.yaml"
  args = ['generate', 'Specification/BrAPI-Schema',
          '-l', 'OPEN_API',
          '-f', filename,
          '-o', optionfilename,
          '-m', metadatafilename,
          '-c', 'Specification/OpenAPI-Components',
          '-x',
          '-t',
          '-r']
}

tasks.register("generateOpenAPIJSON", JavaExec) {
  group = 'BrAPI'
  description = 'Generate Single JSON OpenAPI schema from the Json Schema'
  classpath = sourceSets.main.runtimeClasspath
  mainClass = javaMainClass
  workingDir = '../'
  def filename = "Specification/Generated/brapi_generated.json"
  def optionfilename = "generator/openapi-single-file-options.yaml"
  def metadatafilename = "generator/openapi-metadata.yaml"
  args = ['generate', 'Specification/BrAPI-Schema',
          '-l', 'OPEN_API_JSON',
          '-f', filename,
          '-o', optionfilename,
          '-m', metadatafilename,
          '-c', 'Specification/OpenAPI-Components',
          '-x',
          '-t',
          '-r']
}


tasks.register("generateOWL", JavaExec) {
  group = 'BrAPI'
  description = 'Generate OWL schema from the Json Schema'
  classpath = sourceSets.main.runtimeClasspath
  mainClass = javaMainClass
  workingDir = '../'
  def filename = "Specification/Generated/brapi_generated.ttl"
  args = ['generate', 'Specification/BrAPI-Schema',
          '-l', 'OWL',
          '-f', filename,
          '-m', 'generator/ont-model-metadata.yaml',
          '-x',
          '-t',
          '-r']
}

tasks.register("generateAll") {
  dependsOn generateGraphQL
  dependsOn generateOpenAPI
  dependsOn generateOpenAPIJSON
  //dependsOn generateOWL
}

tasks.register("compareOpenAPI", JavaExec) {
  group = 'BrAPI'
  description = 'Compare the compiled OpenAPI schema from the YAML files with the one generated from the Json Schema'
  dependsOn copyOpenApi
  dependsOn generateOpenAPIJSON
  classpath = sourceSets.main.runtimeClasspath
  mainClass = javaMainClass
  workingDir = '../'
  def filename1 = "Specification/Generated/brapi_openapi.json"
  def filename2 = "Specification/Generated/brapi_generated.json"
  def filename = "Specification/Generated/brapi_openapi_comparison.md"
  args = ['compare', filename1, filename2,
          '-l', 'OPEN_API',
          '-f', filename,
          '-w', 'MARKDOWN',
          '-c', 'Specification/OpenAPI-Components',
          '-x',
          '-t',
          '-r']
}

tasks.register("compareAll") {
  dependsOn compareOpenAPI
  mustRunAfter generateAll
}

tasks.register("runAll") {
  dependsOn generateAll
  dependsOn compareAll
}
