info:
  title: BrAPI
  version: ''
openapi: 3.1.0
paths: {}
components:
  schemas:
    SeedLotTransactionNewRequest:
      type: object
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestricted by the BrAPI specification.
          type:
            - object
            - 'null'
        transactionDescription:
          description: A general description of this Seed Lot Transaction
          type:
            - string
            - 'null'
          example: f9cd88d2
        transactionTimestamp:
          description: The time stamp for when the transaction occurred
          type:
            - string
            - 'null'
          format: date-time
        toSeedLotDbId:
          description: The identifier for the Seed Lot being transferred into
          type:
            - string
            - 'null'
          example: 59339b90
        fromSeedLotDbId:
          description: The identifier for the Seed Lot being transferred out of
          type:
            - string
            - 'null'
          example: 11eef13b
        amount:
          description: The number of units being transferred between SeedLots. Could be a count (seeds, bulbs, etc) or a weight (kg of seed).
          type:
            - number
            - 'null'
          example: 45
        units:
          description: A description of the things being transferred between SeedLots in a transaction (seeds, bulbs, kg, etc)
          type:
            - string
            - 'null'
          example: seeds
        externalReferences:
          anyOf:
            - $ref: '#/components/schemas/ExternalReferences'
            - type: 'null'


