info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    OntologyNewRequest:
      type: object
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestriced by the BrAPI specification.
          type: object
        authors:
          description: Ontology's list of authors (no specific format)
          type: string
          example: Bob Robertson, Rob Robertson
        copyright:
          description: Ontology copyright
          type: string
          example: Copyright 1987, Bob Robertson
        description:
          description: Human readable description of Ontology
          type: string
          example: This is an example ontology that does not exist 
        documentationURL:
          description: A URL to the human readable documentation of an object
          format: uri
          type: string
          example: https://wiki.brapi.org/ontology
        licence:
          description: Ontology licence
          type: string
          example: MIT Open source licence
        ontologyName:
          description: Ontology name
          type: string
          example: The Official Ontology
        version:
          description: Ontology version (no specific format)
          type: string
          example: V1.3.2

