components:
  schemas:
    ReferenceSet:
      description: |-
        A `ReferenceSet` is a set of `Reference` s which typically comprise a
        reference assembly, such as `GRCh38`. A `ReferenceSet` defines a common
        coordinate space for comparing reference-aligned experimental data.
      properties:
        assembly_id:
          description: |-
            The remaining information is about the source of the sequences
            Public id of this reference set, such as `GRCh37`.
          type: string
        attributes:
          $ref: '#/components/schemas/Attributes'
        description:
          description: Optional free text description of this reference set.
          type: string
        id:
          description: The reference set ID. Unique in the repository.
          type: string
        is_derived:
          description: |-
            A reference set may be derived from a source if it contains
            additional sequences, or some of the sequences within it are derived
            (see the definition of `isDerived` in `Reference`).
          format: boolean
          type: boolean
        md5checksum:
          description: |-
            Order-independent MD5 checksum which identifies this `ReferenceSet`.

            To compute this checksum, make a list of `Reference.md5checksum` for all
            `Reference` s in this set. Then sort that list, and take the MD5 hash of
            all the strings concatenated together. Express the hash as a lower-case
            hexadecimal string.
          type: string
        name:
          description: The reference set name.
          type: string
        source_accessions:
          description: |-
            All known corresponding accession IDs in INSDC (GenBank/ENA/DDBJ) ideally
            with a version number, e.g. `NC_000001.11`.
          items:
            type: string
          type: array
        source_uri:
          description: Specifies a FASTA format file/string.
          type: string
        species:
          $ref: '#/components/schemas/OntologyTerm'
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
