info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Call:
      description: |-
        A `Call` represents the determination of genotype with respect to a particular `Variant`.

        It may include associated information such as quality and phasing. For example, a call might assign a probability of 0.32 to the occurrence of a SNP named RS_1234 in a call set with the name NA_12345.
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        callSetDbId:
          description: |-
            The ID of the call set this variant call belongs to.

            If this field is not present, the ordering of the call sets from a `SearchCallSetsRequest` over this `VariantSet` is guaranteed to match the ordering of the calls on this `Variant`. The number of results will also be the same.
          type: string
        callSetName:
          description: The name of the call set this variant call belongs to. If this field is not present, the ordering of the call sets from a `SearchCallSetsRequest` over this `VariantSet` is guaranteed to match the ordering of the calls on this `Variant`. The number of results will also be the same.
          type: string
        variantDbId:
          description: The ID of the variant this call belongs to.
          type: string
        variantName:
          description: The name of the variant this call belongs to.
          type: string
        genotype:
          $ref: '#/components/schemas/ListValue'
        genotype_likelihood:
          description: The genotype likelihood for this variant call. Each array entry represents how likely a specific genotype is for this call as log10(P(data | genotype)), analogous to the GL tag in the VCF spec. The value ordering is defined by the GL tag in the VCF spec.
          items:
            format: double
            type: number
          type: array
        phaseSet:
          description: If this field is populated, this variant call's genotype ordering implies the phase of the bases and is consistent with any other variant calls on the same contig which have the same phase set string.
          type: string
      type: object

