info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /seedlots/transactions:
    get:
      summary: Get a filtered list of Seed Lot Transactions
      description: Get a filtered list of Seed Lot Transactions
      parameters:
      - name: transactionDbId
        description: Unique id for a transaction on this server
        in: query
        required: false
        schema:
          type: string 
      - name: seedLotDbId
        description: Unique id for a seed lot on this server
        in: query
        required: false
        schema:
          type: string 
      - name: germplasmDbId
        description: The internal id of the germplasm
        in: query
        required: false
        schema:
          type: string 
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/SeedLotTransactionListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Seed Lots
    post:
      summary: Add new Seed Lot Transaction to be recorded
      description: Add new Seed Lot Transaction to be recorded
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                seedLots:
                  type: array
                  items: 
                    $ref: '#/components/schemas/SeedLotNewTransactionRequest'
      responses:
        '200':
          $ref: '#/components/responses/SeedLotTransactionListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Seed Lots
components:
  responses:
    SeedLotTransactionListResponse:
      content:
        application/json:
          schema:
            title: SeedLotTransactionListResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/SeedLotTransaction'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
      description: OK
      headers: {}
