services:
  build-docs:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../Specification:/src/Specification
      - ../build:/src/build
    working_dir: /src
    command: ["./Scripts/buildDocs.sh" ]
  gen-swagger:
    volumes:
      - ../Specification:/src/Specification
      - ../build:/src/build
    image: swaggerapi/swagger-codegen-cli
    command: generate -i /src/build/brapi_openapi.yaml -l openapi -o /src/Specification