services:
  build-docs:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../Specification:/src/Specification
      - ../build:/src/build
    working_dir: /src
    command: ["./Scripts/buildDocs.sh" ]