version: '2.5.1'
services:
  build-docs:
    build: ..
    volumes:
      - ./Specification:/src/Specification
      - ./build:/src/build
    working_dir: /src
    command: ["./Scripts/buildDocs.sh" ]

