info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Metric:
      allOf:
      - $ref: '#/components/schemas/MetricNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Phenotyping
        title: Metric
        description: The prediction value as an output of some analysis
        required:
        - metricDbId
        properties:
          metricDbId:
            description: The unique identifier of a Metric
            type: string
            example: 5ceb9fa5


          


          

