info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Prediction:
      allOf:
      - $ref: '#/components/schemas/PredictionNewRequest'
      - type: object
        x-brapi-metadata:
          primaryModel: true
          module: BrAPI-Phenotyping
        title: Prediction
        description: The prediction value as an output of some analysis
        required:
        - predictionDbId
        properties:
          predictionDbId:
            description: The unique identifier of a Prediction
            type: string
            example: 43ab644f

          

