info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ProgramNewRequest:
      type: object
      required:
      - programName
      properties:
        abbreviation:
          description: A shortened version of the human readable name for a Program
          type: string
          example: P1
        additionalInfo:
          additionalProperties:
            type: string
          description: A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestriced by the BrAPI specification.
          type: object
        commonCropName:
          description: Common name for the crop which this program is for
          type: string
          example: Tomatillo
        documentationURL:
          description: A URL to the human readable documentation of an object
          format: uri
          type: string
          example: https://wiki.brapi.org
        leadPersonDbId:
          description: The unique identifier of the program leader
          type: string
          example: fe6f5c50
        leadPersonName:
          description: The name of the program leader
          type: string
          example: Bob Robertson
        objective:
          description: The primary objective of the program
          type: string
          example: Make a better tomatillo
        programName:
          description: Human readable name of the program
          type: string
          example: Tomatillo_Breeding_Program
        programType:
          description: |-
            The type of program entity this object represents
            <br/> 'STANDARD' represents a standard, permenant breeding program
            <br/> 'PROJECT' represents a short term project, usually with a set time limit based on funding   
          type: string
          enum:
          - STANDARD
          - PROJECT
          example: STANDARD
        fundingInformation:
          description: Information describing the grant or funding source for this program
          type: string
          example: 'EU: FP7-244374'
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
          

