info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /calls:
    get:
      summary: Gets a filtered list of `Calls`
      description: '
        `GET /call` will return a filtered list of `Call` JSON objects.
        
        Also See:
        
        `GET /callsets/{callsetsDbId}/calls`
        
        `GET /variants/{variantsDbId}/calls`
        
        `GET /variantsets/{variantsetsDbId}/calls`
        '
      parameters:
        - name: callSetDbId
          description: The ID of the `CallSet` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - name: variantDbId
          description: The ID of the `Variant` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - name: variantSetDbId
          description: The ID of the `VariantSet` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                properties:
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        items:
                          $ref: '#/components/schemas/Call'
                        type: array
                    required:
                    - data
                    title: callListResponseResult
                    type: object
                required:
                - metadata
                - result
                title: callListResponse
                type: object
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Calls