info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /search/variants/{searchResultsDbId}:
    get:
      summary: Gets a list of `Variant` matching the search criteria.
      description: >-
        `POST /variants/search` must accept a JSON version of

        `SearchVariantsRequest` as the post body and will return a JSON version
        of

        `SearchVariantsResponse`.
      parameters:
      - $ref: '#/components/parameters/searchResultsDbId'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                properties:
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        items:
                          $ref: '#/components/schemas/Variant'
                        type: array
                    required:
                    - data
                    title: variantListResponseResult
                    type: object
                required:
                - metadata
                - result
                title: variantListResponse
                type: object
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Variants