info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /variants/{variantDbId}/calls:
    get:
      summary: Gets a list of `Calls` associated with a `Variant`.
      description: '
        The variant calls for this particular variant. Each one represents the
        determination of genotype with respect to this variant. `Call`s in this
        array are implicitly associated with this `Variant`.
      
        Also See:
        
        `GET /calls?variantDbId={variantDbId}`
        '
      parameters:
        - name: variantDbId
          description: The ID of the `Variant` to be retrieved.
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                properties:
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        items:
                          $ref: '#/components/schemas/Call'
                        type: array
                    required:
                    - data
                    title: callListResponseResult
                    type: object
                required:
                - metadata
                - result
                title: callListResponse
                type: object
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Variants