info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    TrialSearchRequest:
      allOf:
      - $ref: '#/components/schemas/SearchRequestParametersPaging'
      - $ref: '#/components/schemas/SearchRequestParametersCommonCropNames'
      - $ref: '#/components/schemas/SearchRequestParametersPrograms'
      - $ref: '#/components/schemas/SearchRequestParametersTrials'
      - $ref: '#/components/schemas/SearchRequestParametersStudies'
      - $ref: '#/components/schemas/SearchRequestParametersLocations'
      - type: object
        properties:
          active:
            description: Is this trail currently active
            type: boolean
            example: true
          contactDbIds:
            description: List of contact entities associated with this trial
            type: array
            items:
              type: string
            example: ['e0f70c2a', 'b82f0967']
          searchDateRangeStart: 
            description: |-
              The start of the overlapping search date range. `searchDateRangeStart` must be before `searchDateRangeEnd`.
              
              Return a Trial entity if any of the following cases are true
              
              - `searchDateRangeStart` is before `trial.endDate` AND `searchDateRangeEnd` is null 
              
              - `searchDateRangeStart` is before `trial.endDate` AND `searchDateRangeEnd` is after `trial.startDate`
              
              - `searchDateRangeEnd` is after `trial.startDate` AND `searchDateRangeStart` is null
              
              - `searchDateRangeEnd` is after `trial.startDate` AND `searchDateRangeStart` is before `trial.endDate`
            format: date
            type: string
          searchDateRangeEnd:
            description: |-
              The end of the overlapping search date range. `searchDateRangeStart` must be before `searchDateRangeEnd`.
              
              Return a Trial entity if any of the following cases are true
              
              - `searchDateRangeStart` is before `trial.endDate` AND `searchDateRangeEnd` is null 
              
              - `searchDateRangeStart` is before `trial.endDate` AND `searchDateRangeEnd` is after `trial.startDate`
              
              - `searchDateRangeEnd` is after `trial.startDate` AND `searchDateRangeStart` is null
              
              - `searchDateRangeEnd` is after `trial.startDate` AND `searchDateRangeStart` is before `trial.endDate`
            format: date
            type: string
          trialPUIs: 
            description: A permanent identifier for a trial. Could be DOI or other URI formatted identifier.
            type: array
            items:
              type: string
            example: ['https://doi.org/01093190', 'https://doi.org/11192409']

