info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    CallsSearchRequest: 
      type: object
      properties:
        pagination:
          description: Pagination for the matrix
          type: array
          items:
            type: object
            properties:
              dimension:
                description: the dimension of the matrix being paginated
                type: string
                example: variants
              pageSize: 
                description: the maximum number of elements per page in this dimension of the matrix
                type: integer
                example: 500
              page: 
                description: the requested page number (zero indexed) 
                type: integer
                example: 0
          example:
            -  dimension: variants
               pageSize: 500
               page: 0
            -  dimension: callsets
               pageSize: 1000
               page: 4
        preview:
          description: |- 
            Default Value = false
            <br/>
            If 'preview' is set to true, then the server should only return the lists of 'callsetDbIds', 
            'variantDbIds', and 'variantSetDbIds'. The server should not return any matrix data. This
            is intended to be a preview and give the client a sense of how large the matrix returned will be
            <br/>
            If 'preview' is set to false or not set (default), then the server should return all the matrix
            data as requested.
          type: boolean
          default: false
          example: true
        positionRanges:
          description: |-
            The postion range to search
            <br/>
            Uses the format "<chrom>:<start>-<end>" where <chrom> is the chromosome name, <start> is 
            the starting position of the range, and <end> is the ending position of the range
          type: array
          items:
            type: string
          example: [ '20:1000-35000', '20:87000-125000' ]
        germplasmNames:
          description: The germplasm to search
          type: array
          items:
            type: string
          example: [ 'a03202ec', '274e4f63' ]
        germplasmPUIs:
          description: The germplasm to search
          type: array
          items:
            type: string
          example: [ 'a03202ec', '274e4f63' ]
        germplasmDbIds:
          description: The germplasm to search
          type: array
          items:
            type: string
          example: [ 'a03202ec', '274e4f63' ]
        sampleDbIds:
          description: The samples to search
          type: array
          items:
            type: string
          example: [ 'a03202ec', '274e4f63' ]
        callSetDbIds:
          description: The CallSet to search.
          type: array
          items:
            type: string
          example: [ 'a03202ec', '274e4f63' ]
        variantDbIds: 
          description: The Variant to search.
          type: array
          items:
            type: string
          example: [ 'bba0b258', 'ff97d4f0' ]
        variantSetDbIds: 
          description: The VariantSet to search.
          type: array
          items:
            type: string
          example: [ '407c0508', '49e24dfc' ]
        expandHomozygotes:
          description: Should homozygotes be expanded (true) or collapsed into a single occurrence (false)
          type: boolean
          example: true
        sepPhased:
          description: The string used as a separator for phased allele calls.
          type: string
          example: '|'
        sepUnphased:
          description: The string used as a separator for unphased allele calls.
          type: string
          example: '/'
        unknownString:
          description: The string used as a representation for missing data.
          type: string
          example: '.'
