info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /callsets/{callSetDbId}/calls:
    get:
      summary: Gets a list of `Calls` associated with a `CallSet`.
      description: Gets a list of `Calls` associated with a `CallSet`.
      parameters:
        - name: callSetDbId
          description: The ID of the `CallSet` to be retrieved.
          in: path
          required: true
          schema:
            type: string
        - name: expandHomozygotes
          description: Should homozygotes be expanded (true) or collapsed into a single occurence (false)
          in: query
          required: false
          schema:
            type: boolean
        - name: unknownString
          description: The string to use as a representation for missing data
          in: query
          required: false
          schema:
            type: string
        - name: sepPhased
          description: The string to use as a separator for phased allele calls
          in: query
          required: false
          schema:
            type: string
        - name: sepUnphased
          description: The string to use as a separator for unphased allele calls
          in: query
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/schemas/CallsListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Call Sets