info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /germplasm:
    get:
      summary: Get a filtered list of Germplasm
      description: |-
        Addresses these needs
        
        - General germplasm search mechanism that accepts POST for complex queries 
        
        - Possibility to search germplasm by more parameters than those allowed by the existing germplasm search 
        
        - Possibility to get MCPD details by PUID rather than dbId
      parameters:
      - name: germplasmPUI
        description: Permanent unique identifier (DOI, URI, etc.)
        in: query
        required: false
        schema:
          type: string
      - name: germplasmDbId
        description: Internal database identifier
        in: query
        required: false
        schema:
          type: string
      - name: germplasmName
        description: Name of the germplasm
        in: query
        required: false
        schema:
          type: string
      - name: commonCropName
        description: The common crop name related to this germplasm
        in: query
        required: false
        schema:
          type: string
      - name: accessionNumber
        description: Unique identifiers for accessions within a genebank
        in: query
        required: false
        schema:
          type: string
      - name: germplasmGenus
        description: Genus name to identify germplasm
        in: query
        required: false
        schema:
          type: string
      - name: germplasmSpecies
        description: Species name to identify germplasm
        in: query
        required: false
        schema:
          type: string
      - name: studyDbId
        description: Search for Germplasm that are associated with a particular Study
        in: query
        required: false
        schema:
          type: string
      - name: synonym 
        description: Alternative name or ID used to reference this germplasm
        in: query
        required: false
        schema:
          type: string
      - name: parentDbId
        description: Search for Germplasm with this parent
        in: query
        required: false
        schema:
          type: string
      - name: progenyDbId
        description: Search for Germplasm with this child
        in: query
        required: false
        schema:
          type: string
      - name: xref
        description: Search for Germplasm by an external reference
        in: query
        required: false
        schema:
          type: string
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/GermplasmListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Germplasm
    post:
      summary: Create new Germplasm entities on this server
      description: Create new Germplasm entities on this server
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: '#/components/schemas/GermplasmNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/GermplasmListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Germplasm
components:
  responses:
    GermplasmListResponse:
      content:
        application/json:
          schema:
            title: GermplasmListResponse
            type: object
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/Germplasm'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
      description: OK
      headers: {}
