info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /search/variantsets/{searchResultsDbId}:
    get:
      summary: Gets a list of `VariantSet` matching the search criteria.
      description: >-
        `POST /variantsets/search` must accept a JSON version of

        `SearchVariantSetsRequest` as the post body and will return a JSON
        version

        of `SearchVariantSetsResponse`.
      parameters:
      - $ref: '#/components/parameters/searchResultsDbId'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        items:
                          $ref: '#/components/schemas/VariantSet'
                        type: array
                    required:
                    - data
                    title: variantSetListResponseResult
                    type: object
                required:
                - metadata
                - result
                title: variantSetListResponse
                type: object
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Variant Sets