info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /variantsets/{variantSetDbId}/callsets:
    get:
      summary: Gets a list of `CallSets` associated with a `VariantSet`.
      description: '
        Gets a list of `CallSets` associated with a `VariantSet`.
      
        Also See:
        
        `GET /callsets?variantSetDbId={variantSetDbId}`
        '
      parameters:
        - name: callSetDbId
          description: The ID of the `CallSet` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - name: callSetName
          description: The human readbale name of the `CallSet` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - name: variantSetDbId
          description: The ID of the `VariantSet` to be retrieved.
          in: path
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        items:
                          $ref: '#/components/schemas/CallSet'
                        type: array
                    required:
                    - data
                    title: callSetsListResponseResult
                    type: object
                required:
                - metadata
                - result
                title: callSetsListResponse
                type: object
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Variant Sets