#! /usr/bin/env python

def getVersions(path, method):
	ret = []
	for version in versions:
		if version['call'] == path and version['method'].lower() == method:
			ret = version['versions']
	return ret


versions = [
{ 'call' : '/allelematrices', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/allelematrices-search', 'method' : 'GET', 'versions':['1.2', '1.3']},
{ 'call' : '/allelematrices-search', 'method' : 'POST', 'versions':['1.2', '1.3']},
{ 'call' : '/allelematrix-search', 'method' : 'GET', 'versions':['1.0', '1.1', ]},
{ 'call' : '/allelematrix-search', 'method' : 'POST', 'versions':['1.0', '1.1', ]},
{ 'call' : '/attributes', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/attributes/categories', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/breedingmethods', 'method' : 'GET', 'versions':['1.2', '1.3']},
{ 'call' : '/breedingmethods/{breedingMethodDbId}', 'method' : 'GET', 'versions':['1.2', '1.3']},
{ 'call' : '/calls', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/commoncropnames', 'method' : 'GET', 'versions':['1.2', '1.3']},
{ 'call' : '/crops', 'method' : 'GET', 'versions':['1.0', '1.1', ]},
{ 'call' : '/germplasm', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/germplasm/{germplasmDbId}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/germplasm/{germplasmDbId}/attributes', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/germplasm/{germplasmDbId}/markerprofiles', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/germplasm/{germplasmDbId}/mcpd', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/germplasm/{germplasmDbId}/pedigree', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/germplasm/{germplasmDbId}/progeny', 'method' : 'GET', 'versions':['1.2', '1.3']},
{ 'call' : '/germplasm-search', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', ]},
{ 'call' : '/germplasm-search', 'method' : 'POST', 'versions':['1.0', '1.1', '1.2', ]},
{ 'call' : '/images', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/images', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/images/{imageDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/images/{imageDbId}', 'method' : 'PUT', 'versions':['1.3']},
{ 'call' : '/images/{imageDbId}/imagecontent', 'method' : 'PUT', 'versions':['1.3']},
{ 'call' : '/lists', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/lists', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/lists/{listDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/lists/{listDbId}', 'method' : 'PUT', 'versions':['1.3']},
{ 'call' : '/lists/{listDbId}/items', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/locations', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/locations/{locationDbId}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/maps', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/maps/{mapDbId}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/maps/{mapDbId}/positions', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/maps/{mapDbId}/positions/{linkageGroupId}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/maps/{mapDbId}/positions/{linkageGroupName}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/markerprofiles', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/markerprofiles/{markerprofileDbId}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/markerprofiles-search', 'method' : 'POST', 'versions':['1.0', ]},
{ 'call' : '/markers', 'method' : 'GET', 'versions':['1.0', '1.3']},
{ 'call' : '/markers/{markerDbId}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/markers-search', 'method' : 'GET', 'versions':['1.1', '1.2', ]},
{ 'call' : '/markers-search', 'method' : 'POST', 'versions':['1.1', '1.2', ]},
{ 'call' : '/methods', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/methods', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/methods/{methodDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/methods/{methodDbId}', 'method' : 'PUT', 'versions':['1.3']},
{ 'call' : '/observationlevels', 'method' : 'GET', 'versions':['1.1', '1.2', '1.3']},
{ 'call' : '/observationLevels', 'method' : 'GET', 'versions':['1.0', ]},
{ 'call' : '/observationunits', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/ontologies', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/people', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/people', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/people/{personDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/people/{personDbId}', 'method' : 'PUT', 'versions':['1.3']},
{ 'call' : '/phenotypes', 'method' : 'POST', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/phenotypes-search', 'method' : 'GET', 'versions':['1.2', ]},
{ 'call' : '/phenotypes-search', 'method' : 'POST', 'versions':['1.0', '1.1', '1.2', ]},
{ 'call' : '/phenotypes-search/csv', 'method' : 'POST', 'versions':['1.2', ]},
{ 'call' : '/phenotypes-search/table', 'method' : 'POST', 'versions':['1.2', ]},
{ 'call' : '/phenotypes-search/tsv', 'method' : 'POST', 'versions':['1.2', ]},
{ 'call' : '/programs', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/programs-search', 'method' : 'POST', 'versions':['1.0', '1.1', '1.2', ]},
{ 'call' : '/samples', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/samples', 'method' : 'PUT', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/samples/{sampleDbId}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/samples-search', 'method' : 'GET', 'versions':['1.1', '1.2', ]},
{ 'call' : '/samples-search', 'method' : 'POST', 'versions':['1.1', '1.2', ]},
{ 'call' : '/scales', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/scales', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/scales/{scaleDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/scales/{scaleDbId}', 'method' : 'PUT', 'versions':['1.3']},
{ 'call' : '/search/germplasm', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/search/germplasm/{searchResultsDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/search/images', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/search/images/{searchResultsDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/search/markers', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/search/markers/{searchResultsDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/search/observationtables', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/search/observationtables/{searchResultsDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/search/observationunits', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/search/observationunits/searchResultsDbId', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/search/programs', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/search/programs/{searchResultsDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/search/samples', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/search/samples/{searchResultsDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/search/studies', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/search/studies/{searchResultsDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/search/variables', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/search/variables/{searchResultsDbId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/seasons', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/studies', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/studies/{studyDbId}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/studies/{studyDbId}/germplasm', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/studies/{studyDbId}/layout', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', ]},
{ 'call' : '/studies/{studyDbId}/layout', 'method' : 'PUT', 'versions':['1.2', ]},
{ 'call' : '/studies/{studyDbId}/layouts', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/studies/{studyDbId}/layouts', 'method' : 'PUT', 'versions':['1.3']},
{ 'call' : '/studies/{studyDbId}/observations', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/studies/{studyDbId}/observations', 'method' : 'PUT', 'versions':['1.2', '1.3']},
{ 'call' : '/studies/{studyDbId}/observationunits', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/studies/{studyDbId}/observationunits', 'method' : 'POST', 'versions':['1.0', ]},
{ 'call' : '/studies/{studyDbId}/observationunits', 'method' : 'PUT', 'versions':['1.1', '1.2', '1.3']},
{ 'call' : '/studies/{studyDbId}/observationunits/zip', 'method' : 'POST', 'versions':['1.1', '1.2', '1.3']},
{ 'call' : '/studies/{studyDbId}/observationvariables', 'method' : 'GET', 'versions':['1.1', '1.2', '1.3']},
{ 'call' : '/studies/{studyDbId}/observationVariables', 'method' : 'GET', 'versions':['1.0', ]},
{ 'call' : '/studies/{studyDbId}/table', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/studies/{studyDbId}/table', 'method' : 'POST', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/studies-search', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', ]},
{ 'call' : '/studies-search', 'method' : 'POST', 'versions':['1.0', '1.1', '1.2', ]},
{ 'call' : '/studytypes', 'method' : 'GET', 'versions':['1.1', '1.2', '1.3']},
{ 'call' : '/studyTypes', 'method' : 'GET', 'versions':['1.0', ]},
{ 'call' : '/token', 'method' : 'DELETE', 'versions':['1.0', '1.1', '1.2', ]},
{ 'call' : '/token', 'method' : 'POST', 'versions':['1.0', '1.1', '1.2', ]},
{ 'call' : '/traits', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/traits', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/traits/{traitDbId}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/traits/{traitDbId}', 'method' : 'PUT', 'versions':['1.3']},
{ 'call' : '/trials', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/trials/{trialDbId}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/variables', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/variables/{observationVariableDbId}', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', '1.3']},
{ 'call' : '/variables/datatypes', 'method' : 'GET', 'versions':['1.0', '1.1', '1.2', ]},
{ 'call' : '/variables-search', 'method' : 'POST', 'versions':['1.0', '1.1', '1.2', ]},
{ 'call' : '/vendor/orders', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/vendor/orders', 'method' : 'POST', 'versions':['1.3']},
{ 'call' : '/vendor/orders/{orderId}/plates', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/vendor/orders/{orderId}/results', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/vendor/orders/{orderId}/status', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/vendor/plate/{vendorPlateDbId}', 'method' : 'GET', 'versions':['1.1', ]},
{ 'call' : '/vendor/plates', 'method' : 'POST', 'versions':['1.2', '1.3']},
{ 'call' : '/vendor/plates/{submissionId}', 'method' : 'GET', 'versions':['1.3']},
{ 'call' : '/vendor/plates/{vendorPlateDbId}', 'method' : 'GET', 'versions':['1.2', ]},
{ 'call' : '/vendor/plate-search', 'method' : 'GET', 'versions':['1.1', ]},
{ 'call' : '/vendor/plate-search', 'method' : 'POST', 'versions':['1.1', ]},
{ 'call' : '/vendor/plates-search', 'method' : 'GET', 'versions':['1.2', ]},
{ 'call' : '/vendor/plates-search', 'method' : 'POST', 'versions':['1.2', ]},
{ 'call' : '/vendor/specifications', 'method' : 'GET', 'versions':['1.1', '1.2', '1.3']}
	]
