info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    VariantSet:
      description: A VariantSet is a collection of variants and variant calls intended to be analyzed together.
      type: object
      x-brapi-metadata:
        primaryModel: true
        module: BrAPI-Genotyping
        title: Variant
        description: A VariantSet is a collection of variants and variant calls intended to be analyzed together.
      required:
      - variantSetDbId
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestriced by the BrAPI specification.
          type: object
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
        availableFormats:
          description: |-
            When the data for a VariantSet is retrieved, it can be retrieved in a variety of data formats and file formats. 
            <br/>'dataFormat' defines the structure of the data within a file (ie DartSeq, VCF, Hapmap, tabular, etc)
            <br/>'fileFormat' defines the MIME type of the file (ie text/csv, application/excel, application/zip). This should also be reflected in the Accept and ContentType HTTP headers for every relevant request and response.
          type: array
          items:
            $ref: '#/components/schemas/AvailableFormat'
        metadataFields:
          description: |-
            The 'metadataFields' array indicates which types of genotyping data and metadata are available in the VariantSet. 
            <br> When possible, these field names and abbreviations should follow the VCF standard 
          type: array
          items:
            description: |-
              This represents a type of genotyping data or metadata available in this VariantSet
            type: object
            properties:
              dataType:
                description: The type of field represented in this Genotype Field. This is intended to help parse the data out of JSON.
                type: string
                enum:
                - string
                - integer
                - float
                - boolean
                example: integer
              fieldName:
                description: |-
                  The name of the field represented in this Genotype Field. Examples include: "Genotype Quality", "Read Depth", and "Haplotype Quality"
                type: string
                example: Genotype Quality
              fieldAbbreviation:
                description: |-
                  The abbreviated code of the field represented in this Genotype Field. These codes should match the VCF standard when possible. Examples include: "GQ", "RD", and "HQ"
                type: string
                example: GQ
        analysis:
          description: Set of Analysis descriptors for this VariantSet 
          type: array
          items:
            $ref: '#/components/schemas/Analysis'
        studyDbId:
          description: The ID of the dataset this variant set belongs to.
          type: string
          example: 2fc3b034
        variantSetDbId: 
          description: The unique identifier for a VariantSet
          type: string
          example: 87a6ac1e
        variantSetName:
          description: The human readable name for a VariantSet
          type: string
          example: Maize QC DataSet 002334 
        variantCount:
          description: The number of Variants included in this VariantSet
          type: integer
          example: 250
        callSetCount:
          description: The number of CallSets included in this VariantSet
          type: integer
          example: 341
        referenceSetDbId:
          description: The ID of the reference set that describes the sequences used by the variants in this set.
          type: string
          example: 57eae639

