info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    VariantSetsSearchRequest: 
      allOf:
      - $ref: '#/components/schemas/SearchRequestParametersPaging'
      - $ref: '#/components/schemas/SearchRequestParametersCommonCropNames'
      - $ref: '#/components/schemas/SearchRequestParametersPrograms'
      - $ref: '#/components/schemas/SearchRequestParametersTrials'
      - $ref: '#/components/schemas/SearchRequestParametersStudies'
      - $ref: '#/components/schemas/SearchRequestParametersExternalReferences'
      - type: object
        properties: 
          callSetDbIds: 
            description: The unique identifier representing a CallSet
            type: array
            items:
              type: string
            example: ['9569cfc4', 'da1e888c']
          variantDbIds: 
            description: The unique identifier representing a Variant
            type: array
            items:
              type: string
            example: ['c80f068b', 'eb7c5f50']
          variantSetDbIds: 
            description: The unique identifier representing a VariantSet 
            type: array
            items:
              type: string
            example: ['b2903842', 'dcbb8558']
          referenceDbIds:
            description: The unique identifier representing a genotype Refernce 
            items:
              type: string
            type: array
            example: ['89ab4d17', '74d3b63d']
          referenceSetDbIds:
            description: The unique identifier representing a genotype RefernceSet 
            items:
              type: string
            type: array
            example: ['d3b63d4d', '3b63d74b']

