info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /commoncropnames:
    get:
      description: "List the common crop names for the crops available in a database server. \n\nThis call is **required** for multi-crop systems where data from multiple crops may be stored in the same database server. A distinct database server is defined by everything in the URL before \"/brapi/v1\", including host name and base path.  \n\nThis call is recommended for single crop systems to be compatible with multi-crop clients. For a single crop system the response should contain an array with exactly 1 element. \n\nThe common crop name can be used as a search parameter for Programs, Studies, and Germplasm.\n\n\ntest-server.brapi.org/brapi/v1/commonCropNames"
      parameters:
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          content:
            application/json:
              example:
                metadata:
                  datafiles: []
                  pagination:
                    currentPage: 0
                    pageSize: 2
                    totalCount: 2
                    totalPages: 1
                  status: []
                result:
                  data:
                  - Tomatillo
                  - Paw Paw
              schema:
                required:
                  - metadata
                  - result
                properties:
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    required:
                      - data
                    properties:
                      data:
                        description: array of crop names availible on the server
                        items:
                          description: supported crop name
                          type: string
                        type: array
                    type: object
                title: commonCropNamesResponse
                type: object
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      summary: Get the Common Crop Names
      tags:
      - Crops
