info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /trials:
    get:
      summary: Get a filtered list of Trials
      description: Retrieve a filtered list of breeding Trials. A Trial is a collection of Studies
      parameters:
      - name: active
        description: Filter active status true/false.
        in: query
        required: false
        schema:
          type: boolean
      - name: contactDbId
        description: Contact entities associated with this trial
        in: query
        required: false
        schema:
          type: string
      - name: locationDbId
        description: Filter by location
        in: query
        required: false
        schema:
          type: string
      - name: searchDateRangeStart
        description: |-
            The start of the overlapping search date range. `searchDateRangeStart` must be before `searchDateRangeEnd`.
            
            Return a Trial entity if any of the following cases are true
            
            - `searchDateRangeStart` is before `trial.endDate` AND `searchDateRangeEnd` is null 
            
            - `searchDateRangeStart` is before `trial.endDate` AND `searchDateRangeEnd` is after `trial.startDate`
            
            - `searchDateRangeEnd` is after `trial.startDate` AND `searchDateRangeStart` is null
            
            - `searchDateRangeEnd` is after `trial.startDate` AND `searchDateRangeStart` is before `trial.endDate`
        in: query
        required: false
        schema:
          type: string
          format: date
      - name: searchDateRangeEnd
        description: |-
            The start of the overlapping search date range. `searchDateRangeStart` must be before `searchDateRangeEnd`.
            
            Return a Trial entity if any of the following cases are true
            
            - `searchDateRangeStart` is before `trial.endDate` AND `searchDateRangeEnd` is null 
            
            - `searchDateRangeStart` is before `trial.endDate` AND `searchDateRangeEnd` is after `trial.startDate`
            
            - `searchDateRangeEnd` is after `trial.startDate` AND `searchDateRangeStart` is null
            
            - `searchDateRangeEnd` is after `trial.startDate` AND `searchDateRangeStart` is before `trial.endDate`
        in: query
        required: false
        schema:
          type: string
          format: date
      - name: studyDbId
        description: Filter by connected studyDbId
        in: query
        required: false
        schema:
          type: string
      - name: trialDbId
        description: Filter by trialDbId
        in: query
        required: false
        schema:
          type: string
      - name: trialName
        description: Filter by trial name
        in: query
        required: false
        schema:
          type: string
      - name: trialPUI
        description: Filter by trial PUI
        in: query
        required: false
        schema:
          type: string
      - name: sortBy
        description: Sort order. Name of the field to sort by.
        in: query
        required: false
        schema:
          enum:
          - trialDbId
          - trialName
          - programDbId
          - programName
          - locationDbId
          - startDate
          - endDate
          type: string
      - name: sortOrder
        description: 'Sort order direction: asc/desc'
        in: query
        required: false
        schema:
          enum:
          - asc
          - ASC
          - desc
          - DESC
          type: string
      - $ref: '#/components/parameters/programDbId'
      - $ref: '#/components/parameters/commonCropName'
      - $ref: '#/components/parameters/externalReferenceID'
      - $ref: '#/components/parameters/externalReferenceSource'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/TrialListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Trials
    post:
      summary: Create new trials
      description: Create new breeding Trials. A Trial represents a collection of related Studies. `trialDbId` is generated by the server.
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: 
                $ref: '#/components/schemas/TrialNewRequest'
      responses:
        '200':
          $ref: '#/components/responses/TrialListResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Trials

components:
  responses:
    TrialListResponse:
      content:
        application/json:
          schema:
            title: TrialListResponse
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  data:
                    items:
                      $ref: '#/components/schemas/Trial'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
            type: object
      description: OK
      headers: {}