info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    OntologyTerm:
      description: An ontology term describing an attribute. (e.g. the phenotype attribute 'polydactyly' from HPO)
      type: object
      properties:
        term:
          description: Ontology term - the label of the ontology term the termId is pointing to.
          type: string
        termURI: 
          description: |-
            Ontology term identifier - the CURIE for an ontology term. It
            differs from the standard GA4GH schema's :ref:`id `
            in that it is a CURIE pointing to an information resource outside of the
            scope of the schema or its resource implementation.
          type: string

