info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ReferenceBases: 
      description: The response from `POST /listreferencebases` expressed as JSON.
      type: object
      properties:
        nextPageToken:
          description: |-
            The continuation token, which is used to page through large result sets.
            Provide this value in a subsequent request to return the next page of
            results. This field will be empty if there aren't any additional results.
          type: string
        offset:
          description: |-
            The offset position (0-based) of the given sequence from the start of this
            `Reference`. This value will differ for each page in a paginated request.
          format: int64
          type: string
        sequence:
          description: |-
            A substring of the bases that make up this reference. Bases are represented
            as IUPAC-IUB codes; this string matches the regexp `[ACGTMRWSYKVHDBN]*`.
          type: string

