info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ReferencesSearchRequest: 
      description: |-
        ****************  /references  *******************
        This request maps to the body of `POST /references/search` as JSON.
      type: object
      properties:
        accession:
          description: |-
            If specified, return the references for which the `accession`
            matches this string (case-sensitive, exact match).
          type: string
        md5checksum:
          description: |-
            If specified, return the references for which the
            `md5checksum` matches this string (case-sensitive, exact match).
            See `ReferenceSet::md5checksum` for details.
          type: string
        page_size:
          description: |-
            Specifies the maximum number of results to return in a single page.
            If unspecified, a system default will be used.
          format: int32
          type: integer
        page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            `next_page_token` from the previous response.
          type: string
        referenceSetDbId:
          description: The `ReferenceSet` to search.
          type: string

