components:
  schemas:
    AttributeValue:
      description: |-
        Type defining a collection of attributes associated with various protocol
        records. Each attribute is a name that maps to an array of one or more
        values. Values are chosen from both internal protobuf types and GA4GH.
         Values should be split into array elements instead of using a separator
        syntax that needs to parsed.
      properties:
        analysis:
          $ref: '#/components/schemas/Analysis'
        attribute_list:
          $ref: '#/components/schemas/AttributeValueList'
        attributes:
          $ref: '#/components/schemas/Attributes'
        bool_value:
          format: boolean
          type: boolean
        double_value:
          format: double
          type: number
        experiment:
          $ref: '#/components/schemas/Experiment'
        external_identifier:
          $ref: '#/components/schemas/ExternalIdentifier'
        int32_value:
          format: int32
          type: integer
        int64_value:
          format: int64
          type: string
        null_value:
          $ref: '#/components/schemas/NullValue'
        ontology_term:
          $ref: '#/components/schemas/OntologyTerm'
        program:
          $ref: '#/components/schemas/Program'
        string_value:
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
