info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /lists/{listDbId}/items:
    post:
      deprecated: true
      description: |-
        **Deprecated in v2.1** Please use `POST /lists/{listDbId}/data`. Github issue number #444 
        <br/> Add new data to a specific generic lists
      parameters:
      - description: The unique ID of this generic list
        in: path
        name: listDbId
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              items:
                type: string
              type: array
              example: ['758a78c0', '2c78f9ee']
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  '@context':
                    $ref: '#/components/schemas/Context'
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    $ref: '#/components/schemas/ListDetails'
                required:
                - metadata
                - result
                title: listResponse
                type: object
          description: OK
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      summary: Add Items to a specific List
      tags:
      - Lists
