info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  responses:
    NIRSMatrixResponse:
      content:
        application/json:
          schema:
            title: NIRSMatrixResponse
            properties:
              '@context':
                $ref: '#/components/schemas/Context'
              metadata:
                $ref: '#/components/schemas/metadata'
              result:
                properties:
                  instanceId:
                    description: Relates data matrix to a specific instance
                    type: string
                    example: abc123
                  uploadTimestamp:
                    description: Timestamp for initial upload of spectral data matrix into database 
                    type: date-time
                    example: 2024-01-03 3:04:05
                  deviceSerialNumber:
                    description: Serial number of the spectrometer device
                    type: string
                    example: ABC1234567
                  protocolDbId:
                    description: description
                    type: string
                    example: fe6f5c50
                  data:
                    items:
                      $ref: '#/components/schemas/ObservationVector'
                    type: array
                required:
                - data
                type: object
            required:
            - metadata
            - result
            type: object
      description: OK
      headers: {}