info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    NIRSInstance:
      title: NIRSInstance
      type: object
      properties:
        instanceId:
          description: Relates data matrix to a specific instance
          type: string
          example: abc123
        uploadTimestamp:
          description: Timestamp for initial upload of spectral data matrix into database 
          type: string
          format: date-time
          example: 2024-01-03 3:04:05
        deviceSerialNumber:
          description: Serial number of the spectrometer device
          type: string
          example: ABC1234567
        protocolDbId:
          description: The ID which uniquely identifies the NIRS protocol 
          type: string
          example: f60f15b2
        columnHeaders:
          description: An ordered list of column header definitions for this instance
          type: array
          example: [{"frequency":740}, {"frequency":742}, {"frequency":744}, {"frequency":746}]
          items:
            type: object
            properties:
              frequency:
                description: Wavelength in nanometers 
                type: integer
