info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    NIRSProtocolNewRequest:
      type: object
      properties:
        protocolTitle:
          description: Human-readable string summarizing the protocol
          type: string
          example: Foss DS3 NIRS protocol for ground butter beans
        protocolDescription:
          description: Human-readable text describing the protocol in more detail
          type: string
          example: Details on sample preparation, calibration, & model used
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
        documentationURL:
          description: Link to detailed Standard Operating Procedure (SOP) for protocol
          format: uri
          type: string
          example: https://wiki.brapi.org
        deviceType:
          description: Spectrometer device name 
          type: string
          example: SCIO
        deviceFrequencyNumber:
          description: Total number of wavelengths measured in each scan of the device
          type: integer
          example: 200
        frequencies:
          description: Wavelength in nanometers 
          type: array
          example: [740, 742, 744, 746]
          items:
            type: integer

          

