info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    CrossingProjectNewRequest:
      type: object
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        crossingProjectName:
          description: the human readable name for a crossing project
          type: string
          example: Ibadan_Crosses_2018
        crossingProjectDescription:
          description: the description for a crossing project
          type: string
          example: Crosses between germplasm X and germplasm Y in male nursery study X_2018 and female nursery study Y_2018
        programDbId:
          description: the unique identifier for a program
          type: string
          example: a088176c
        programName:
          description: the human readable name for a program
          type: string
          example: IITA Cassava
        commonCropName:
          description: the common name of a crop (for multi-crop systems)
          type: string
          example: Cassava
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
          
        