info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    CrossingProjectNewRequest:
      type: object
      required:
      - crossingProjectName
      properties:
        additionalInfo:
          additionalProperties:
            type: string
          description: A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestriced by the BrAPI specification.
          type: object
        crossingProjectName:
          description: The human readable name for a crossing project
          type: string
          example: Crosses_2018
        crossingProjectDescription:
          description: the description for a crossing project
          type: string
          example: Crosses between germplasm X and germplasm Y in male nursery study X_2018 and female nursery study Y_2018
        programDbId:
          description: the unique identifier for a program
          type: string
          example: a088176c
        programName:
          description: the human readable name for a program
          type: string
          example: IITA Cassava
        commonCropName:
          description: the common name of a crop (for multi-crop systems)
          type: string
          example: Cassava
        potentialParents:
          description: |-
            A list of all the potential parents in the crossing block, available in the crossing project
            <br/> If the parameter 'includePotentialParents' is false, the array 'potentialParents' should be empty, null, or excluded from the response object.
          type: array
          items:
            $ref: '#/components/schemas/CrossParent'
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
          
        