info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    Germplasm:
      allOf:
      - $ref: '#/components/schemas/GermplasmNewRequest'
      - type: object
        required:
        - germplasmDbId
        properties: 
          germplasmDbId:
            description: |-
              The ID which uniquely identifies a germplasm within the given database server
              
              MIAPPE V1.1 (DM-41) Biological material ID - Code used to identify the biological material in the data file. Should be unique within the Investigation. Can correspond to experimental plant ID, seed lot ID, etc. This material identification is different from a BiosampleID which corresponds to Observation Unit or Samples sections below.
            type: string
            example: d4076594