info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ObservationUnitSearchRequest: 
      allOf:
      - $ref: '#/components/schemas/SearchRequestParametersPaging'
      - $ref: '#/components/schemas/SearchRequestParametersCommonCropNames'
      - $ref: '#/components/schemas/SearchRequestParametersPrograms'
      - $ref: '#/components/schemas/SearchRequestParametersTrials'
      - $ref: '#/components/schemas/SearchRequestParametersStudies'
      - $ref: '#/components/schemas/SearchRequestParametersLocations'
      - $ref: '#/components/schemas/SearchRequestParametersGermplasm'
      - $ref: '#/components/schemas/SearchRequestParametersObservationVariables'
      - $ref: '#/components/schemas/SearchRequestParametersExternalReferences'
      - type: object
        properties:
          observationUnitDbIds:
            description: The unique id of an observation unit
            items:
              type: string
            type: array
            example: ['66bab7e3', '0e5e7f99']
          observationUnitNames:
            description: The human readable identifier for an Observation Unit
            items:
              type: string
            type: array
            example: ['FieldA_PlotB', 'SpecialPlantName']
          observationLevels: 
            description: Searches for values in ObservationUnit->observationUnitPosition->observationLevel
            type: array 
            items: 
              $ref: '#/components/schemas/ObservationUnitLevelRelationship'
            example:
              - levelName: plot
                levelCode: Plot_123
              - levelName: plot
                levelCode: Plot_456
              - levelName: plot
                levelCode: Plot_789
          observationLevelRelationships: 
            description: Searches for values in ObservationUnit->observationUnitPosition->observationLevelRelationships
            type: array 
            items: 
              $ref: '#/components/schemas/ObservationUnitLevelRelationship'
            example:
              - levelName: field
                levelCode: Field_1
          includeObservations: 
            description: |-
              Use this parameter to include a list of observations embedded in each ObservationUnit object. 
              
              CAUTION - Use this parameter at your own risk. It may return large, unpaginated lists of observation data. Only set this value to True if you are sure you need to.
            type: boolean
            example: False

