info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
components:
  schemas:
    ReferenceSet:
      description: A `ReferenceSet` is a set of `Reference` s which typically comprise a reference assembly, such as `GRCH_38`. A `ReferenceSet` defines a common coordinate space for comparing reference-aligned experimental data.
      type: object
      x-brapi-metadata:
        primaryModel: true
        module: BrAPI-Genotyping
        title: ReferenceSet
        description: A `ReferenceSet` is a set of `Reference` s which typically comprise a reference assembly, such as `GRCH_38`. A `ReferenceSet` defines a common coordinate space for comparing reference-aligned experimental data.
      required:
      - referenceSetDbId
      - referenceSetName
      properties:
        assemblyPUI:
          description: The remaining information is about the source of the sequences Public id of this reference set, such as `GRCH_37`.
          type: string
          example: 'doi://10.12345/fake/9876'
        additionalInfo:
          additionalProperties:
            type: string
          description: A free space containing any additional information related to a particular object. A data source may provide any JSON object, unrestriced by the BrAPI specification.
          type: object
        externalReferences: 
          $ref: '#/components/schemas/ExternalReferences'
        description:
          description: Optional free text description of this reference set.
          type: string
          example: This is an example description for an assembly
        referenceSetDbId:
          description: The unique identifier for a ReferenceSet
          type: string
          example: c1ecfef1
        referenceSetName:
          description: The human readable name of a ReferenceSet
          type: string
          example: The Best Assembly Ever
        isDerived:
          description: A reference set may be derived from a source if it contains additional sequences, or some of the sequences within it are derived (see the definition of `isDerived` in `Reference`).
          format: boolean
          type: boolean
        md5checksum:
          description: |-
            Order-independent MD5 checksum which identifies this `ReferenceSet`.

            To compute this checksum, make a list of `Reference.md5checksum` for all
            `Reference` s in this set. Then sort that list, and take the MD5 hash of
            all the strings concatenated together. Express the hash as a lower-case
            hexadecimal string.
          type: string
          example: c2365e900c81a89cf74d83dab60df146
        sourceGermplasm:
          description: All known corresponding Germplasm
          type: array
          items:
            type: object
            properties:
              germplasmDbId:
                description: The ID which uniquely identifies a germplasm within the given database server
                type: string
                example: d4076594
              germplasmName:
                description: The human readable name of a germplasm
                type: string
                example: A0000003
        sourceAccessions:
          description: All known corresponding accession IDs in INSDC (GenBank/ENA/DDBJ) ideally with a version number, e.g. `NC_000001.11`.
          items:
            type: string
          type: array
          example: ["A0000002", "A0009393"]
        sourceURI:
          description: Specifies a FASTA format file/string.
          type: string
          example: https://wiki.brapi.org/files/demo.fast
        commonCropName:
          description: Common name for the crop 
          type: string
          example: Maize
        species:
          $ref: '#/components/schemas/OntologyTerm'

