info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /metabolomics/matrix:
    get:
      summary: Get a matrix of Metabolomics data
      description: Get a matrix of Metabolomics data. A valid request must include a "protocolDbId", an "instanceDbId", or both.
      parameters:
      - name: instanceDbId
        description: A unique identifier for a Metabolomics Instance
        in: query
        required: false
        schema:
          type: string
      - name: protocolDbId
        description: A unique identifier for a Metabolomics Protocol
        in: query
        required: false
        schema:
          type: string
      - name: observationUnitDbId
        description: A unique identifier for an Observation Unit
        in: query
        required: false
        schema:
          type: string
      - name: sampleDbId
        description: A unique identifier for a field sample
        in: query
        required: false
        schema:
          type: string
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          $ref: '#/components/responses/MetabolomicsMatrixResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - High-Dimensional-Phenotypes
#    post:
#      summary: Submit a new matrix
#      description: Submit a new matrix
#      parameters:
#      - name: metabolomicsProtocolDbId
#        description: Filter by the common crop name. Exact match.
#        in: path
#        required: true
#        schema:
#          type: string
#      - $ref: '#/components/parameters/authorizationHeader'
#      requestBody:
#        content:
#          application/json:
#            schema:
#              $ref: '#/components/schemas/MatrixNewRequest'
#      responses:
#        '200':
#          $ref: '#/components/responses/MatrixResponse'
#        '400':
#          $ref: '#/components/responses/400BadRequest'
#        '401':
#          $ref: '#/components/responses/401Unauthorized'
#        '403':
#          $ref: '#/components/responses/403Forbidden'
#      tags:
#      - High-Dimensional-Phenotypes
#    put:
#      summary: Update an existing matrix
#      description: Update an existing matrix 
#      parameters:
#      - name: metabolomicsProtocolDbId
#        description: Filter by the common crop name. Exact match.
#        in: path
#        required: true
#        schema:
#          type: string
#      - $ref: '#/components/parameters/authorizationHeader'
#      requestBody:
#        content:
#          application/json:
#            schema:
#              $ref: '#/components/schemas/MatrixNewRequest'
#      responses:
#        '200':
#          $ref: '#/components/responses/MatrixResponse'
#        '400':
#          $ref: '#/components/responses/400BadRequest'
#        '401':
#          $ref: '#/components/responses/401Unauthorized'
#        '403':
#          $ref: '#/components/responses/403Forbidden'
#      tags:
#      - High-Dimensional-Phenotypes

